version: '3.8'

services:
  musicstream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicstream-app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 